### ISSUE TITLE
Help or docs?

### ISSUE THREAD

**Issue by InflamedSebi** [NicoSchlueter/HelicalGear#13]
Hey, I m trying to generate a worm gear and a gear rack with this, but I am failing ... Is this even possible and if so, is there any help on how to do so?

**Comment by phossystems** [comment]
There is currently no official documentation, I hope to create some once the current development cycle is done.

It is possible to create worm gears, they are simply helical gears with just one tooth (in the case of single-start worm gears) and a high helix angle.
To get started you could try a helix angle of 85 deg and a teeth value of 1 and maybe a thickness of 50mm.
You can check the preview checkbox to see your changes in real-time.

A matching worm wheel would need to have the same module and a helix angle of 90 minus the helix angle of the worm gear, so 5 deg in this case. If you wanted a reduction of 1:30 that worm wheel would need 30 teeth.

Racks are currently in development, so they cannot be yet created with the regular version.
You will need to download the development branch to create racks and the development branch still has some bugs.

Hope this helps!

**Comment by InflamedSebi** [comment]
This helps a lot :) Ty.
