### ISSUE TITLE
Feature request: Bevel gears

### ISSUE THREAD

**Issue by soostdijck** [NicoSchlueter/HelicalGear#14]
It would be great if this add on would be able to do bevel gears as well. The only working addon that exists costs 20$ for th basic version. Other then that there does not seem to be anything out there.

Thanks for the great addon so far!

**Comment by phossystems** [comment]
Thank you!
I hope to support bevel and spiral bevel gears in the future, however I do not think it will happen anytime soon.
There is another bevel gear addon for free on the fusion360 app store, have you tried that?

**Comment by soostdijck** [comment]
The one I've found is broken, it has a couple issues open but no reponses...
https://github.com/padarom/bevel-gear.git

**Comment by phossystems** [comment]
I haven't tested it but I found this one and it has good reviews.

https://apps.autodesk.com/FUSION/en/Detail/Index?id=2791960362914790676&appLang=en&os=Win64

**Comment by soostdijck** [comment]
Ah yes, I had seen that one but ignored it since I'm normally on a mac. I've fired up the 'ol windows box and installed that bevel add on, but it seems to be broken for the latest f360 version. I've left a review for it, we'll see if anything happens.

**Comment by phossystems** [comment]
You can most likely just copy the add-in folder from windows to mac, it's only the installer that is os-dependant (except in rare cases).
