### ISSUE TITLE
Addendum/Dedendum Radial Gear Standard

### ISSUE THREAD

**Issue by jono-vision** [NicoSchlueter/HelicalGear#19]
First time basically using GitHub so Im probably doing this wrong. 
But I noticed while I was trying to edit the addendum and dedendum of a gear under the radial setting that nothing happened.

![image](https://user-images.githubusercontent.com/60055216/78506362-43f09100-7736-11ea-8b2a-47a4b4a6b6ff.png)

 gear.addendum = gear.module
        gear.wholeDepth = 2.25 * gear.module

I believe should be:
 gear.addendum = addendum*gear.module
        gear.wholeDepth = (addendum+dedendum) * gear.module

**Comment by phossystems** [comment]
Whoops, must have missed that when implementing addendum and dedendum control.
Will fix it right away! Thanks!

**Comment by phossystems** [comment]
Should now be fixed in GitHub, F360 app store will take a few days to update.

**Comment by jono-vision** [comment]
Awesome thanks!
