### ISSUE TITLE
Addendum & Dedendum settings not working

### ISSUE THREAD

**Issue by Badbabyboyo** [NicoSchlueter/HelicalGear#22]
I haven't seen anyone have this issue anywhere, but when I try to adjust the Addendum or Dedendum factor it has no effect on my gear. Is this supposed to be adjustable? I'm running Windows 10 and the latest version of Fusion 360 as of 05/30/20.

**Comment by Badbabyboyo** [comment]
My bad I see it has already been fixed in another issue. I'll edit my code until the fix is published

**Comment by phossystems** [comment]
Sorry about that, the submission process is a bit involved with a whole review process. Once I get #21 & #18 integrated I will update the app store version.

**Comment by Badbabyboyo** [comment]
Oh no worries thanks for adding all these features to the original program. I can make a lot more adjustments with yours. Is #19 actually fixed though because I changed the code just like you submitted but it still doesn't seem to work in the Radial system. Looks like there may be an issue higher up around line 375.

**Comment by phossystems** [comment]
Are you using the current version of the master branch?
Everything seems to be working fine on my end.

<img width="776" alt="Screenshot 2020-05-30 at 20 58 28" src="https://user-images.githubusercontent.com/30301307/83337057-9d99b580-a2b8-11ea-86c4-94e977dfade7.png">

**Comment by Badbabyboyo** [comment]
No that's probably it, I'll switch to the GIT version then. I just made the fix for #19 on the latest app store version. Thanks!
