### ISSUE TITLE
Gear does not update with user parameter change

### ISSUE THREAD

**Issue by joshmaceachern** [NicoSchlueter/HelicalGear#23]
Title says most of it. I'd like to be able to adjust the features via user parameters that can be changed later, but it doesn't seem like this is at all possible. Can this be added?

**Comment by phossystems** [comment]
This is sadly impossible with the current Fusion360 API. There is no reasonable way to create a custom timeline object that could recompute the gear, nor an event handler that could be hacked to do so. 
The current parametric design capabilities are insufficient to create a parameter-driven gear, at least for the method this add-in uses to creat gears.
While there are probably workarounds to be found with enough time, like maybe having a second add-in that identifies gear objects, deletes them, and creates new ones in their place, It is not really feasible to do so.
