### ISSUE TITLE
Editing the feature doesn't show parameters

### ISSUE THREAD

**Issue by daniel-scatigno** [NicoSchlueter/HelicalGear#24]
Hi, before anything, thanks a Lot for the development of this plugin, it's really usefull!

When trying to edit the feature it doesn't show any thing.
![image](https://user-images.githubusercontent.com/1984798/87858559-199d9a80-c905-11ea-974d-de87577e8470.png)
It just show Editing Base Feature but we can't actually edit it!

Im not used to work with plugins on Fusion 360, so is this normal or is it a Bug?

**Comment by phossystems** [comment]
Sadly this is normal. 
The Fusion360 API does not allow the creation of custom features. There is no way to implement the ability to edit the gear afterwards, it has to be deleted and replaced.
