### ISSUE TITLE
feature request: elephant foot bevel or fillet option

### ISSUE THREAD

**Issue by jschoch** [NicoSchlueter/HelicalGear#26]
Wondering if you can add a chamfer or fillet option for the edges to prevent the "elephant foot" effect on the first layer when printing.  It is very hard to select all of the edges in a high tooth count gear.  Maybe there is an easier way to select the edges and use the standard tools.

**Comment by phossystems** [comment]
Sorry for the extremely late reply,
but in case anyone stumbles across this, you can (now) just select the bottom face in the chamfer tool to apply a chamfer to all it's edges.

Also most slicers allow you to have an elephant foot compensation where it offsets the first layer inwards.

I do not think adding this to the addin is useful as it is beyond normal gear generation.
