### ISSUE TITLE
Internal crossed helical gear

### ISSUE THREAD

**Issue by Yllesia** [NicoSchlueter/HelicalGear#34]
Hi, i need to reproduce an internal crossed helical gear as you have made in your presentation picture.
I circled the connection i need to reproduce in the picture below : 
![image](https://user-images.githubusercontent.com/90132055/146530480-92e76f54-67a2-4fd3-a9c7-fa8391b4f84f.png)
I don't succeed to reproduce those gears with the pluggin, please could you explain how you did it ?
Thank you for your time,
Yllesia.

**Comment by phossystems** [comment]
Hello, the setting for the internal crossed gear are similar to this:

**Comment by phossystems** [comment]
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/30301307/228054964-07ea1711-a403-4a87-a25e-e3157e647b7d.png">
