### ISSUE TITLE
After installing via app store, not seeing menu options to use add-in

### ISSUE THREAD

**Issue by elbowdonkey** [NicoSchlueter/HelicalGear#36]
I've just installed the macOS version of the add-in using the App-store. After restarting Fusion 360, I can't find the add-in anywhere. It's not under "Solid > Create".

I'll try downloading the `.zip` file directly and installing it through the "Utilities > Add-Ins" menu to see if that makes a difference.

**Comment by elbowdonkey** [comment]
I cloned the repo instead of downloading a zip file, then went to "Utilities > Add-Ins", clicked the + icon, navigated to the base folder, and the add-in is now listed under "My Add-Ins".

However, upon restarting Fusion 360, the add-in is no longer in my list of add-ins.

If I add it again, then before restarting Fusion 360, click on "Run", nothing happens.

I suspect something may have changed with how Add-Ins are incorporated into Fusion 360 that now prevent this add-in from installing or even working.

**Comment by phossystems** [comment]
Weird, I just tired installing it from the App Store on MacOS 13.2.1 and it worked fine.
If you still see it in the AddIn utilities window you can right-click on it, view it in finder and delete it and try again.
The path for me is /Users/<username>/Library/Containers/com.autodesk.mas.fusion360/Data/Library/Application Support/Autodesk/ApplicationPlugins/HelicalGearPlus.bundle

<img width="1430" alt="Screenshot 2023-03-27 at 14 57 29" src="https://user-images.githubusercontent.com/30301307/228053560-598fa909-ab0a-44d4-93a8-3a73a8500a6e.png">

**Comment by elbowdonkey** [comment]
I cleared out any previous installs then reinstalled it without issue. It's not clear why it wouldn't work at first, but now it's working without issue. :shrug:

Also, thanks for making this!

**Comment by kuworking** [comment]
Should be reopened. I have installed now (three times already) and I don't know where does it install. The bundle works as expected (it says it is installed), but it doesn't appear in the Fusion360 menu, and I cannot find it.

In the path mentioned above, I have an emtpy folder.

Macbook M2 here.
